CuQuizFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from classroom.views import classroom, students, teachers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classroom.urls')),
    path('accounts/', students.CustomLoginView.as_view(), name='login'),
    path('accounts/logout/', students.CustomLogoutView.as_view(), name='logout'),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

classroom/urls.py
from django.urls import include, path

from .views import classroom, students, teachers, blog

urlpatterns = [
    path('', classroom.home, name='home'),
    path('post/', blog.PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', blog.UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>', blog.PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update/', blog.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', blog.PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', blog.PostCreateView.as_view(), name='post-create'),

    path('students/', include(([
                                   path('', students.QuizListView.as_view(), name='quiz_list'),
                                   path('s/', students.StudentList.as_view(), name='student_list'),
                                   path('interests/', students.StudentInterestsView.as_view(),
                                        name='student_interests'),
                                   path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
                                   path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
                                   path('quiz/<int:pk>/studentresults/', students.QuizResultsView.as_view(),
                                        name='student_quiz_results'),
                               ], 'classroom'), namespace='students')),

    path('teachers/', include(([
                                   path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
                                   path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
                                   path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
                                   path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
                                   path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(),
                                        name='quiz_results'),
                                   path('quiz/<int:pk>/student/<int:student_pk>/',
                                        teachers.QuizResultsStudentView.as_view(), name='quiz_results_student'),
                                   path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
                                   path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change,
                                        name='question_change'),
                                   path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/',
                                        teachers.QuestionDeleteView.as_view(), name='question_delete'),
                                   path('s/', teachers.StudentList.as_view(), name='student_list'),
                               ], 'classroom'), namespace='teachers')),
]

classroom/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe
from django.urls import reverse
from django.utils import timezone


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    username = models.CharField(error_messages={'unique': 'მომხმარებლის სახელი დაკავებულია.'}, max_length=150, unique=True, verbose_name='მომხმარებლის სახელი')


class Subject(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Quiz(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField("დასახელება", max_length=255)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name=u'საგანი',
                                related_name='quizzes')

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField('Question')

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    interests = models.ManyToManyField(Subject, related_name='interested_students')

    # User reputation score.
    score = models.IntegerField(default=0)

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username


class TakenQuiz(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.IntegerField()
    percentage = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')


class Post(models.Model):
    title = models.CharField("სათაური", max_length=100)
    content = models.TextField("პოსტი")
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk' : self.pk})

classroom/views/blog.py
from django.shortcuts import render, get_object_or_404
from ..models import Post
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model

User = get_user_model()


class PostListView(ListView):
    model = Post
    template_name = 'classroom/blog/homeBlog.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class UserPostListView(ListView):
    model = Post
    template_name = 'classroom/blog/user_posts.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post
    template_name = 'classroom/blog/post_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'classroom/blog/post_form.html'
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'classroom/blog/post_form.html'
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'classroom/blog/post_confirm_delete.html'
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'classroom/blog/post_form.html'
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False

classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:quiz_change_list')
        elif request.user.is_student:
            return redirect('students:quiz_list')
        else:
            return redirect('admin:index')
    return render(request, 'classroom/home.html')

classroom/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

from django.db import transaction
from django.db.models import Count, Sum
from django.db.models.functions import Concat
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView
from django.views import View

from ..decorators import student_required
from ..forms import StudentInterestsForm, StudentSignUpForm, TakeQuizForm,CustomAuthenticationForm
from ..models import Quiz, Student, TakenQuiz, Question

from django.contrib.auth.views import LoginView, LogoutView


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm


class CustomLogoutView(LogoutView):
    authentication_form = CustomAuthenticationForm


User = get_user_model()


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'მოსწავლე'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:quiz_list')


@method_decorator([login_required, student_required], name='dispatch')
class StudentInterestsView(UpdateView):
    model = Student
    form_class = StudentInterestsForm
    template_name = 'classroom/students/interests_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'ინტერესები წარმატებულად განახლდა')
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name',)
    context_object_name = 'quizzes'
    template_name = 'classroom/students/quiz_list.html'

    def get_queryset(self):
        student = self.request.user.student
        # student_interests = student.interests.values_list('pk', flat=True)
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.exclude(pk__in=taken_quizzes) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student_subjects'] = self.request.user.student.interests.values_list('pk', flat=True)
        return context


@method_decorator([login_required, student_required], name='dispatch')
class QuizResultsView(View):
    template_name = 'classroom/students/quiz_result.html'

    def get(self, request, *args, **kwargs):
        quiz = Quiz.objects.get(id=kwargs['pk'])
        taken_quiz = TakenQuiz.objects.filter(student=request.user.student, quiz=quiz)
        if not taken_quiz:
            """
            რომ არ ნახოს მოსწავლემ პასუხები ქვიზში მონაწილეობის გარეშე
            """
            return render(request, '404.html')
        questions = Question.objects.filter(quiz=quiz)

        # questions = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'questions': questions,
                                                    'quiz': quiz, 'percentage': taken_quiz[0].percentage})


@method_decorator([login_required, student_required], name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'classroom/students/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz', 'quiz__subject') \
            .order_by('quiz__name')
        return queryset


@login_required
@student_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student

    if student.quizzes.filter(pk=pk).exists():
        questions = Question.objects.filter(quiz=quiz)
        template_name = 'classroom/students/quiz_result.html'
        taken_quiz = TakenQuiz.objects.filter(student=request.user.student, quiz=quiz)
        return render(request, template_name, {'questions': questions,
                                               'quiz': quiz, 'percentage': taken_quiz[0].percentage})

    total_questions = quiz.questions.count()
    unanswered_questions = student.get_unanswered_questions(quiz)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save()
                if student.get_unanswered_questions(quiz).exists():
                    return redirect('students:take_quiz', pk)
                else:
                    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz,
                                                                  answer__is_correct=True).count()
                    percentage = round((correct_answers / total_questions) * 100.0, 2)
                    TakenQuiz.objects.create(student=student, quiz=quiz, score=correct_answers, percentage=percentage)
                    student.score = TakenQuiz.objects.filter(student=student).aggregate(Sum('score'))['score__sum']
                    student.save()
                    if percentage < 50.0:
                        messages.warning(request, 'წარმატებები შემდეგ ჯერზე, შენი შეფასება ქვიზისთვის: %s არის %s.' % (
                            quiz.name, percentage))
                    else:
                        messages.success(request,
                                         'გილოცავ! შენ შეასრულე ქვიზი: %s წარმატებით! შენი შეფასებაა %s ქულა.' % (
                                             quiz.name, percentage))
                    # return redirect('students:quiz_list')
                    return redirect('students:student_quiz_results', pk)
    else:
        form = TakeQuizForm(question=question)

    return render(request, 'classroom/students/take_quiz_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'progress': progress,
        'answered_questions': total_questions - total_unanswered_questions,
        'total_questions': total_questions
    })


@method_decorator([login_required, student_required], name='dispatch')
class StudentList(ListView):
    # model = get_user_model()
    paginate_by = 36
    template_name = 'classroom/students/student_list.html'
    context_object_name = 'students'

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        User = get_user_model()

        queryset = Student.objects.order_by('-score')
        if query:
            # queryset = queryset.annotate(
            #     full_name = Concat('first_name','last_name')
            # ).filter(full_name__icontains = query)
            queryset = queryset.filter(user__username__icontains=query)
        return queryset

classroom/templates/classroom/teachers/_header.html
<div style="margin-right: 15px; padding: 15px; border:1px; border-style:solid; border-color:gray; border-radius: 10px">
    <h2>კატეგორია</h2>
    <ul class="nav flex-column nav-pills">
        <div>
            <li class="nav-item">
                <a class="nav-link{% if active == 'new' %} active{% endif %}"
                   href="{% url 'teachers:quiz_change_list' %}">ქვიზები</a>
            </li>
        </div>

        <div>
            <li class="nav-item">
                <a class="nav-link{% if active == 'students' %} active{% endif %}"
                   href="{% url 'teachers:student_list' %}">მოსწავლეები</a>
            </li>
        </div>
        <div>
            <li class="nav-item">
                <a class="nav-link{% if active == 'post' %} active{% endif %}"
                   href="{% url 'blog-home' %}">პოსტები</a>
            </li>
        </div>
        <div>
            <li class="nav-item">
                <a class="nav-link{% if active == 'post-create' %} active{% endif %}"
                   href="{% url 'post-create' %}">პოსტის დამატება</a>
            </li>
        </div>
    </ul>
</div>

classroom/templates/classroom/teachers/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">ჩემი ქვიზები</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">ახალი შეკითხვის დამატება</li>
    </ol>
  </nav>
  <h2 class="mb-3">ახალი შეკითხვის ჩამატება</h2>
  <p class="lead">დაამატეთ შეკითხვა პირველ რიგში რათა შეძლოთ სავარაუდო პასუხების ჩამატება.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">შენახვა</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">უარყოფა</a>
  </form>
{% endblock %}

classroom/templates/classroom/teachers/question_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">ჩემი ქვიზები</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>პასუხები</strong>
          </div>
          <div class="col-2">
            <strong>სწორია?</strong>
          </div>
          <div class="col-2">
            <strong>გსურთ წაშლა?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>ძველი პასუხი:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <button type="submit" class="btn btn-success">ცლილებების შენახვა</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">უარყოფა</a>
    <a href="{% url 'teachers:question_delete' quiz.pk question.pk %}" class="btn btn-danger float-right">წაშლა</a>
  </form>
{% endblock %}

classroom/templates/classroom/teachers/question_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">ჩემი ქვიზები</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">წაშლის დადასტურება</h2>
  <p class="lead">დარწმუნებული ხართ რომ გსურთ წაშალოთ <strong>"{{ question.text }}"</strong>? სამუდამოდ </p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">თანხმობა</button>
    <a href="{% url 'teachers:question_change' quiz.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">უარყოფა</a>
  </form>
{% endblock %}

classroom/templates/classroom/teachers/quiz_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">ჩემი ქვიზები</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ quiz.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ quiz.name }}
    <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary float-right">შეფასების ნახვა</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">ცვლილების შენახვა</button>
        <a href="{% url 'teachers:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">უარყოფა</a>
        <a href="{% url 'teachers:quiz_delete' quiz.pk %}" class="btn btn-danger float-right">წაშლა</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>შეკითხვები</strong>
        </div>
        <div class="col-2">
          <strong>პასუხები</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">ჯერჯერობით არ შეგიქმნიათ პირვეი შეკითხვა <a href="{% url 'teachers:question_add' quiz.pk %}">პირველი შეკითხვის დამატება</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'teachers:question_add' quiz.pk %}" class="btn btn-primary btn-sm">შეკითხვის დამატება</a>
    </div>
  </div>
{% endblock %}

classroom/templates/classroom/teachers/quiz_change_list.html
{% extends 'base.html' %}

{% block content %}
    <div id = responsivediv>
        <div>
            {% include 'classroom/teachers/_header.html' with active='new' %}
        </div>
        <div>
            <h2 class="mb-3">ჩემი ქვიზები</h2>
            <a href="{% url 'teachers:quiz_add' %}" class="btn btn-primary mb-3" role="button">ქვიზის დამატება</a>
            <div class="card" style="overflow-x:auto;">
                <table class="table mb-0">
                    <thead>
                    <tr>
                        <th>ქვიზი</th>
                        <th>საგანი</th>
                        <th>შეკითხვა</th>
                        <th>მონაწილეობა მიღებული</th>
                        <th>გაზიარება</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for quiz in quizzes %}
                        <tr>
                            <td class="align-middle"><a
                                    href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
                            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
                            <td class="align-middle">{{ quiz.questions_count }}</td>
                            <td class="align-middle">{{ quiz.taken_count }}</td>
                            <td>
                                <a href="https://www.facebook.com/sharer/sharer.php?u=https://cu-quiz-io.herokuapp.com/students/quiz/{{ quiz.id }}/">Facebook</a>
                            </td>
                            <td class="text-right">
                                <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary">შეფასების
                                    ნახვა</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="bg-light text-center font-italic" colspan="5">თქვენ არ შეგიქმნიათ ჯერჯერობით
                                არცერთი ქვიზი.
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

classroom/templates/classroom/teachers/quiz_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">ჩემი ქვიზები</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">წაშლის დადასტურება</li>
    </ol>
  </nav>
  <h2 class="mb-3">წაშლის დადასტურება</h2>
  <p class="lead">ნამდვილად გსურთ ქვიზის: <strong>"{{ quiz.name }}"</strong> სამუდამოდ წაშლა?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">თანხმობა</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary btn-lg" role="button">უარყოფა</a>
  </form>
{% endblock %}

classroom/templates/classroom/teachers/quiz_results.html
{% extends 'base.html' %}

{% load crispy_forms_tags humanize %}

{% block content %}
    <div id=responsivediv>
        <div>
            {% include 'classroom/teachers/_header.html' with active='new' %}
        </div>
        <div style="width: 100%">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">ჩემი ქვიზები</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">შეფასება</li>
                </ol>
            </nav>
            <h2 class="mb-3">{{ quiz.name }} შეფასება</h2>

            <div class="card" style="overflow-x:auto;">
                <table class="table mb-0">
                    <thead>
                    <tr>
                        <th>მოსწავლე</th>
                        <th>თარიღი</th>
                        <th>პროცენტულობა</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for taken_quiz in taken_quizzes %}
                        <tr>
                            <td>
                                <a href="{% url 'teachers:quiz_results_student' taken_quiz.quiz.id taken_quiz.student.user.id %}"
                                   class="btn btn-primary">{{ taken_quiz.student.user.username }}</a></td>
                            <td>{{ taken_quiz.date|naturaltime }}</td>
                            <td>{{ taken_quiz.percentage }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div id = responsivediv1 class="card-footer text-muted">
                სულ მონაწილეობა მიიღო: <strong>{{ total_taken_quizzes }}</strong>
                <strong><span style="font-size:15px"
                              class="badge badge-pill badge-primary float-right">საშუალო ქულა: {{ quiz_score.average_score|default_if_none:0.0 }}</span></strong>
            </div>
        </div>
    </div>
{% endblock %}